#
# Module manifest for module 'MicrosoftTeams'
#
# Generated by: Microsoft Corporation
#
# Updated on: 6/30/2020
#

@{
# Script module or binary module file associated with this manifest.
RootModule = './MicrosoftTeams.psm1'

# Version number of this module.
ModuleVersion = '5.2.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd910df43-3ca6-4c9c-a2e3-e9f45a8e2ad9'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core.

For more information, please visit the following: https://docs.microsoft.com/MicrosoftTeams/teams-powershell-overview'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# Removed this script from here because this module is used in SAW machines as well where Contraint Language Mode is on.
# Because of CLM constraint we were not able to import Teams module to SAW machines, that is why removing this script.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
#NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport =  @(
    'Clear-CsOnlineTelephoneNumberOrder'
	,'Complete-CsOnlineTelephoneNumberOrder'
	,'Disable-CsMeetingRoom'
	,'Disable-CsOnlineSipDomain'
#preview	,'Disable-CsTeamsShiftsConnectionErrorReport'
	,'Enable-CsOnlineSipDomain'
	,'Export-CsAutoAttendantHolidays'
	,'Export-CsOnlineAudioFile'
	,'Find-CsGroup'
	,'Find-CsOnlineApplicationInstance'
	,'Get-CsApplicationAccessPolicy'
	,'Get-CsApplicationMeetingConfiguration'
	,'Get-CsAutoAttendant'
	,'Get-CsAutoAttendantHolidays'
	,'Get-CsAutoAttendantStatus'
	,'Get-CsAutoAttendantSupportedLanguage'
	,'Get-CsAutoAttendantSupportedTimeZone'
	,'Get-CsAutoAttendantTenantInformation'
	,'Get-CsBatchPolicyAssignmentOperation'
	,'Get-CsCallingLineIdentity'
	,'Get-CsCallQueue'
	,'Get-CsCloudCallDataConnection'
	,'Get-CsDialPlan'
	,'Get-CsEffectiveTenantDialPlan'
	,'Get-CsGroupPolicyAssignment'
	,'Get-CsHybridTelephoneNumber'
	,'Get-CsInboundBlockedNumberPattern'
	,'Get-CsInboundExemptNumberPattern'
	,'Get-CsMeetingMigrationStatus'
	,'Get-CsOnlineApplicationInstance'
	,'Get-CsOnlineApplicationInstanceAssociation'
	,'Get-CsOnlineApplicationInstanceAssociationStatus'
	,'Get-CsOnlineAudioConferencingRoutingPolicy'
	,'Get-CsOnlineAudioFile'
	,'Get-CsOnlineDialInConferencingBridge'
	,'Get-CsOnlineDialInConferencingLanguagesSupported'
	,'Get-CsOnlineDialinConferencingPolicy'
	,'Get-CsOnlineDialInConferencingServiceNumber'
	,'Get-CsOnlineDialinConferencingTenantConfiguration'
	,'Get-CsOnlineDialInConferencingTenantSettings'
	,'Get-CsOnlineDialInConferencingUser'
	,'Get-CsOnlineDialOutPolicy'
	,'Get-CsOnlineDirectoryTenant'
	,'Get-CsOnlineEnhancedEmergencyServiceDisclaimer'
	,'Get-CsOnlineLisCivicAddress'
	,'Get-CsOnlineLisLocation'
	,'Get-CsOnlineLisPort'
	,'Get-CsOnlineLisSubnet'
	,'Get-CsOnlineLisSwitch'
	,'Get-CsOnlineLisWirelessAccessPoint'
	,'Get-CsOnlinePowerShellEndpoint'
	,'Get-CsOnlinePSTNGateway'
	,'Get-CsOnlinePstnUsage'
	,'Get-CsOnlineSchedule'
	,'Get-CsOnlineSipDomain'
	,'Get-CsOnlineTelephoneNumber'
	,'Get-CsOnlineTelephoneNumberCountry'
	,'Get-CsOnlineTelephoneNumberOrder'
	,'Get-CsOnlineTelephoneNumberType'
	,'Get-CsOnlineUser'
	,'Get-CsOnlineVoicemailUserSettings'
	,'Get-CsOnlineVoiceRoute'
	,'Get-CsOnlineVoiceRoutingPolicy'
	,'Get-CsOnlineVoiceUser'
	,'Get-CsPhoneNumberAssignment'
	,'Get-CsPolicyPackage'
	,'Get-CsPrivacyConfiguration'
#preview	,'Get-CsSdgBulkSignInRequestStatus'
#preview	,'Get-CsSDGBulkSignInRequestsSummary'
	,'Get-CsTeamsAcsFederationConfiguration'
	,'Get-CsTeamsAudioConferencingPolicy'
	,'Get-CsTeamsCallParkPolicy'
	,'Get-CsTeamsClientConfiguration'
	,'Get-CsTeamsComplianceRecordingApplication'
	,'Get-CsTeamsCortanaPolicy'
	,'Get-CsTeamsEducationAssignmentsAppPolicy'
	,'Get-CsTeamsEducationConfiguration'
	,'Get-CsTeamsEmergencyCallRoutingPolicy'
	,'Get-CsTeamsEnhancedEncryptionPolicy'
	,'Get-CsTeamsFilesPolicy'
	,'Get-CsTeamsGuestCallingConfiguration'
	,'Get-CsTeamsGuestMeetingConfiguration'
	,'Get-CsTeamsGuestMessagingConfiguration'
	,'Get-CsTeamsIPPhonePolicy'
	,'Get-CsTeamsMediaLoggingPolicy'
	,'Get-CsTeamsMeetingBroadcastConfiguration'
	,'Get-CsTeamsMeetingBroadcastPolicy'
	,'Get-CsTeamsMeetingConfiguration'
	,'Get-CsTeamsMigrationConfiguration'
	,'Get-CsTeamsMobilityPolicy'
	,'Get-CsTeamsNetworkRoamingPolicy'
	,'Get-CsTeamsNotificationAndFeedsPolicy'
	,'Get-CsTeamsRoomVideoTeleConferencingPolicy'
	,'Get-CsTeamsSettingsCustomApp'
	,'Get-CsTeamsShiftsAppPolicy'
	,'Get-CsTeamsShiftsConnectionConnector'
	,'Get-CsTeamsShiftsConnectionErrorReport'
	,'Get-CsTeamsShiftsConnection'
	,'Get-CsTeamsShiftsConnectionInstance'
	,'Get-CsTeamsShiftsConnectionOperation'
	,'Get-CsTeamsShiftsConnectionSyncResult'
	,'Get-CsTeamsShiftsConnectionTeamMap'
	,'Get-CsTeamsShiftsConnectionWfmTeam'
	,'Get-CsTeamsShiftsConnectionWfmUser'
	,'Get-CsTeamsShiftsPolicy'
	,'Get-CsTeamsSurvivableBranchAppliance'
	,'Get-CsTeamsSurvivableBranchAppliancePolicy'
	,'Get-CsTeamsTargetingPolicy'
	,'Get-CsTeamsTranslationRule'
	,'Get-CsTeamsUnassignedNumberTreatment'
	,'Get-CsTeamsUpgradeConfiguration'
	,'Get-CsTeamsUpgradePolicy'
	,'Get-CsTeamsVdiPolicy'
	,'Get-CsTeamsVideoInteropServicePolicy'
	,'Get-CsTeamsWorkLoadPolicy'
	,'Get-CsTeamTemplate'
	,'Get-CsTeamTemplateList'
	,'Get-CsTenant'
	,'Get-CsTenantBlockedCallingNumbers'
	,'Get-CsTenantDialPlan'
	,'Get-CsTenantFederationConfiguration'
	,'Get-CsTenantLicensingConfiguration'
	,'Get-CsTenantMigrationConfiguration'
	,'Get-CsTenantNetworkConfiguration'
	,'Get-CsTenantNetworkRegion'
	,'Get-CsTenantNetworkSite'
	,'Get-CsTenantNetworkSubnet'
	,'Get-CsTenantTrustedIPAddress'
	,'Get-CsUserCallingSettings'
	,'Get-CsUserPolicyAssignment'
	,'Get-CsUserPolicyPackage'
	,'Get-CsUserPolicyPackageRecommendation'
	,'Get-CsVideoInteropServiceProvider'
    ,'Get-CsTeamsComplianceRecordingPolicy'
	,'Grant-CsApplicationAccessPolicy'
	,'Grant-CsCallingLineIdentity'
	,'Grant-CsDialoutPolicy'
	,'Grant-CsGroupPolicyPackageAssignment'
	,'Grant-CsOnlineAudioConferencingRoutingPolicy'
	,'Grant-CsOnlineVoicemailPolicy'
	,'Grant-CsOnlineVoiceRoutingPolicy'
	,'Grant-CsTeamsAudioConferencingPolicy'
	,'Grant-CsTeamsCallHoldPolicy'
	,'Grant-CsTeamsCallParkPolicy'
	,'Grant-CsTeamsChannelsPolicy'
	,'Grant-CsTeamsCortanaPolicy'
	,'Grant-CsTeamsEmergencyCallingPolicy'
	,'Grant-CsTeamsEmergencyCallRoutingPolicy'
	,'Grant-CsTeamsEnhancedEncryptionPolicy'
	,'Grant-CsTeamsFeedbackPolicy'
	,'Grant-CsTeamsFilesPolicy'
	,'Grant-CsTeamsIPPhonePolicy'
	,'Grant-CsTeamsMediaLoggingPolicy'
	,'Grant-CsTeamsMeetingBroadcastPolicy'
	,'Grant-CsTeamsMeetingPolicy'
	,'Grant-CsTeamsMessagingPolicy'
	,'Grant-CsTeamsMobilityPolicy'
	,'Grant-CsTeamsRoomVideoTeleConferencingPolicy'
	,'Grant-CsTeamsShiftsPolicy'
	,'Grant-CsTeamsSurvivableBranchAppliancePolicy'
	,'Grant-CsTeamsUpdateManagementPolicy'
	,'Grant-CsTeamsUpgradePolicy'
	,'Grant-CsTeamsVdiPolicy'
	,'Grant-CsTeamsVideoInteropServicePolicy'
	,'Grant-CsTeamsVoiceApplicationsPolicy'
	,'Grant-CsTeamsWorkLoadPolicy'
	,'Grant-CsTenantDialPlan'
	,'Grant-CsUserPolicyPackage'
    ,'Grant-CsTeamsComplianceRecordingPolicy'
	,'Import-CsAutoAttendantHolidays'
	,'Import-CsOnlineAudioFile'
	,'Invoke-CsInternalPSTelemetry'
	,'Move-CsInternalHelper'
	,'New-CsApplicationAccessPolicy'
	,'New-CsAutoAttendant'
	,'New-CsAutoAttendantCallableEntity'
	,'New-CsAutoAttendantCallFlow'
	,'New-CsAutoAttendantCallHandlingAssociation'
	,'New-CsAutoAttendantDialScope'
	,'New-CsAutoAttendantMenu'
	,'New-CsAutoAttendantMenuOption'
	,'New-CsAutoAttendantPrompt'
	,'New-CsBatchPolicyAssignmentOperation'
	,'New-CsBatchPolicyPackageAssignmentOperation'
	,'New-CsCallingLineIdentity'
	,'New-CsCallQueue'
	,'New-CsCloudCallDataConnection'
	,'New-CsCustomPolicyPackage'
	,'New-CsEdgeAllowAllKnownDomains'
	,'New-CsEdgeAllowList'
	,'New-CsEdgeDomainPattern'
	,'New-CsGroupPolicyAssignment'
	,'New-CsHybridTelephoneNumber'
	,'New-CsInboundBlockedNumberPattern'
	,'New-CsInboundExemptNumberPattern'
	,'New-CsOnlineApplicationInstance'
	,'New-CsOnlineApplicationInstanceAssociation'
	,'New-CsOnlineAudioConferencingRoutingPolicy'
	,'New-CsOnlineDateTimeRange'
	,'New-CsOnlineLisCivicAddress'
	,'New-CsOnlineLisLocation'
	,'New-CsOnlinePSTNGateway'
	,'New-CsOnlineSchedule'
	,'New-CsOnlineTelephoneNumberOrder'
	,'New-CsOnlineTimeRange'
	,'New-CsOnlineVoiceRoute'
	,'New-CsOnlineVoiceRoutingPolicy'
#preview	,'New-CsSdgBulkSignInRequest'
	,'New-CsTeamsAudioConferencingPolicy'
	,'New-CsTeamsCallParkPolicy'
	,'New-CsTeamsComplianceRecordingApplication'
	,'New-CsTeamsComplianceRecordingPairedApplication'
	,'New-CsTeamsCortanaPolicy'
	,'New-CsTeamsEmergencyCallRoutingPolicy'
	,'New-CsTeamsEmergencyNumber'
	,'New-CsTeamsEnhancedEncryptionPolicy'
	,'New-CsTeamsFilesPolicy'
	,'New-CsTeamsIPPhonePolicy'
	,'New-CsTeamsMeetingBroadcastPolicy'
	,'New-CsTeamsMobilityPolicy'
	,'New-CsTeamsNetworkRoamingPolicy'
	,'New-CsTeamsRoomVideoTeleConferencingPolicy'
	,'New-CsTeamsShiftsConnectionBatchTeamMap'
	,'New-CsTeamsShiftsConnection'
	,'New-CsTeamsShiftsConnectionInstance'
	,'New-CsTeamsShiftsPolicy'
	,'New-CsTeamsSurvivableBranchAppliance'
	,'New-CsTeamsSurvivableBranchAppliancePolicy'
	,'New-CsTeamsTranslationRule'
	,'New-CsTeamsUnassignedNumberTreatment'
	,'New-CsTeamsVdiPolicy'
	,'New-CsTeamsWorkLoadPolicy'
	,'New-CsTeamTemplate'
	,'New-CsTenantDialPlan'
	,'New-CsTenantNetworkRegion'
	,'New-CsTenantNetworkSite'
	,'New-CsTenantNetworkSubnet'
	,'New-CsTenantTrustedIPAddress'
	,'New-CsUserCallingDelegate'
	,'New-CsVideoInteropServiceProvider'
	,'New-CsVoiceNormalizationRule'
    ,'New-CsTeamsComplianceRecordingPolicy'
	,'Register-CsOnlineDialInConferencingServiceNumber'
	,'Remove-CsApplicationAccessPolicy'
	,'Remove-CsAutoAttendant'
	,'Remove-CsCallingLineIdentity'
	,'Remove-CsCallQueue'
	,'Remove-CsCustomPolicyPackage'
	,'Remove-CsGroupPolicyAssignment'
	,'Remove-CsHybridTelephoneNumber'
	,'Remove-CsInboundBlockedNumberPattern'
	,'Remove-CsInboundExemptNumberPattern'
	,'Remove-CsOnlineApplicationInstanceAssociation'
	,'Remove-CsOnlineAudioConferencingRoutingPolicy'
	,'Remove-CsOnlineAudioFile'
	,'Remove-CsOnlineDialInConferencingTenantSettings'
	,'Remove-CsOnlineLisCivicAddress'
	,'Remove-CsOnlineLisLocation'
	,'Remove-CsOnlineLisPort'
	,'Remove-CsOnlineLisSubnet'
	,'Remove-CsOnlineLisSwitch'
	,'Remove-CsOnlineLisWirelessAccessPoint'
	,'Remove-CsOnlinePSTNGateway'
	,'Remove-CsOnlineSchedule'
	,'Remove-CsOnlineTelephoneNumber'
	,'Remove-CsOnlineVoiceRoute'
	,'Remove-CsOnlineVoiceRoutingPolicy'
	,'Remove-CsPhoneNumberAssignment'
	,'Remove-CsTeamsAudioConferencingPolicy'
	,'Remove-CsTeamsCallParkPolicy'
	,'Remove-CsTeamsComplianceRecordingApplication'
	,'Remove-CsTeamsCortanaPolicy'
	,'Remove-CsTeamsEmergencyCallRoutingPolicy'
	,'Remove-CsTeamsEnhancedEncryptionPolicy'
	,'Remove-CsTeamsFilesPolicy'
	,'Remove-CsTeamsIPPhonePolicy'
	,'Remove-CsTeamsMeetingBroadcastPolicy'
	,'Remove-CsTeamsMobilityPolicy'
	,'Remove-CsTeamsNetworkRoamingPolicy'
	,'Remove-CsTeamsNotificationAndFeedsPolicy'
	,'Remove-CsTeamsRoomVideoTeleConferencingPolicy'
    ,'Remove-CsTeamsShiftsConnectionInstance'
    ,'Remove-CsTeamsShiftsConnectionTeamMap'
	,'Remove-CsTeamsShiftsPolicy'
	,'Remove-CsTeamsShiftsScheduleRecord'
	,'Remove-CsTeamsSurvivableBranchAppliance'
	,'Remove-CsTeamsSurvivableBranchAppliancePolicy'
	,'Remove-CsTeamsTargetingPolicy'
	,'Remove-CsTeamsTranslationRule'
	,'Remove-CsTeamsUnassignedNumberTreatment'
	,'Remove-CsTeamsVdiPolicy'
	,'Remove-CsTeamsWorkLoadPolicy'
	,'Remove-CsTeamTemplate'
	,'Remove-CsTenantDialPlan'
	,'Remove-CsTenantNetworkRegion'
	,'Remove-CsTenantNetworkSite'
	,'Remove-CsTenantNetworkSubnet'
	,'Remove-CsTenantTrustedIPAddress'
	,'Remove-CsUserCallingDelegate'
	,'Remove-CsVideoInteropServiceProvider'
    ,'Remove-CsTeamsComplianceRecordingPolicy'
	,'Set-CsApplicationAccessPolicy'
	,'Set-CsApplicationMeetingConfiguration'
	,'Set-CsAutoAttendant'
	,'Set-CsCallingLineIdentity'
	,'Set-CsCallQueue'
	,'Set-CsInboundBlockedNumberPattern'
	,'Set-CsInboundExemptNumberPattern'
	,'Set-CsInternalOnlinePowerShellEndpoint'
	,'Set-CsOnlineApplicationInstance'
	,'Set-CsOnlineAudioConferencingRoutingPolicy'
	,'Set-CsOnlineDialInConferencingBridge'
	,'Set-CsOnlineDialInConferencingServiceNumber'
	,'Set-CsOnlineDialInConferencingTenantSettings'
	,'Set-CsOnlineDialInConferencingUser'
	,'Set-CsOnlineDialInConferencingUserDefaultNumber'
	,'Set-CsOnlineEnhancedEmergencyServiceDisclaimer'
	,'Set-CsOnlineLisCivicAddress'
	,'Set-CsOnlineLisLocation'
	,'Set-CsOnlineLisPort'
	,'Set-CsOnlineLisSubnet'
	,'Set-CsOnlineLisSwitch'
	,'Set-CsOnlineLisWirelessAccessPoint'
	,'Set-CsOnlinePSTNGateway'
	,'Set-CsOnlinePstnUsage'
	,'Set-CsOnlineSchedule'
	,'Set-CsOnlineVoiceApplicationInstance'
	,'Set-CsOnlineVoicemailUserSettings'
	,'Set-CsOnlineVoiceRoute'
	,'Set-CsOnlineVoiceRoutingPolicy'
	,'Set-CsOnlineVoiceUser'
	,'Set-CsPhoneNumberAssignment'
	,'Set-CsPrivacyConfiguration'
	,'Set-CsTeamsAcsFederationConfiguration'
	,'Set-CsTeamsAudioConferencingPolicy'
	,'Set-CsTeamsCallParkPolicy'
	,'Set-CsTeamsClientConfiguration'
	,'Set-CsTeamsComplianceRecordingApplication'
	,'Set-CsTeamsCortanaPolicy'
	,'Set-CsTeamsEducationAssignmentsAppPolicy'
	,'Set-CsTeamsEducationConfiguration'
	,'Set-CsTeamsEmergencyCallRoutingPolicy'
	,'Set-CsTeamsEnhancedEncryptionPolicy'
	,'Set-CsTeamsFilesPolicy'
	,'Set-CsTeamsGuestCallingConfiguration'
	,'Set-CsTeamsGuestMeetingConfiguration'
	,'Set-CsTeamsGuestMessagingConfiguration'
	,'Set-CsTeamsIPPhonePolicy'
	,'Set-CsTeamsMeetingBroadcastConfiguration'
	,'Set-CsTeamsMeetingBroadcastPolicy'
	,'Set-CsTeamsMeetingConfiguration'
	,'Set-CsTeamsMigrationConfiguration'
	,'Set-CsTeamsMobilityPolicy'
	,'Set-CsTeamsNetworkRoamingPolicy'
	,'Set-CsTeamsNotificationAndFeedsPolicy'
	,'Set-CsTeamsRoomVideoTeleConferencingPolicy'
	,'Set-CsTeamsSettingsCustomApp'
	,'Set-CsTeamsShiftsAppPolicy'
 	,'Set-CsTeamsShiftsConnection'
	,'Set-CsTeamsShiftsConnectionInstance'
	,'Set-CsTeamsShiftsPolicy'
	,'Set-CsTeamsSurvivableBranchAppliance'
	,'Set-CsTeamsSurvivableBranchAppliancePolicy'
	,'Set-CsTeamsTargetingPolicy'
	,'Set-CsTeamsTranslationRule'
	,'Set-CsTeamsUnassignedNumberTreatment'
	,'Set-CsTeamsUpgradeConfiguration'
	,'Set-CsTeamsVdiPolicy'
	,'Set-CsTeamsWorkLoadPolicy'
	,'Set-CsTenantBlockedCallingNumbers'
	,'Set-CsTenantDialPlan'
	,'Set-CsTenantFederationConfiguration'
	,'Set-CsTenantMigrationConfiguration'
	,'Set-CsTenantNetworkRegion'
	,'Set-CsTenantNetworkSite'
	,'Set-CsTenantNetworkSubnet'
	,'Set-CsTenantTrustedIPAddress'
	,'Set-CsUser'
	,'Set-CsUserCallingDelegate'
	,'Set-CsUserCallingSettings'
	,'Set-CsVideoInteropServiceProvider'
    ,'Set-CsTeamsComplianceRecordingPolicy'
	,'Start-CsExMeetingMigration'
	,'Sync-CsOnlineApplicationInstance'
	,'Test-CsEffectiveTenantDialPlan'
	,'Test-CsInboundBlockedNumberPattern'
    ,'Test-CsTeamsShiftsConnectionValidate'
	,'Test-CsTeamsTranslationRule'
	,'Test-CsTeamsUnassignedNumberTreatment'
	,'Test-CsVoiceNormalizationRule'
	,'Unregister-CsOnlineDialInConferencingServiceNumber'
	,'Update-CsAutoAttendant'
	,'Update-CsCustomPolicyPackage'
	,'Update-CsTeamsShiftsConnection'
	,'Update-CsTeamsShiftsConnectionInstance'
	,'Update-CsTeamTemplate'
	,'New-CsBatchTeamsDeployment'
	,'Get-CsBatchTeamsDeploymentStatus'
#OCE related functions exports start here. DO NOT MODIFY!
    ,'Set-CsOCEContext'
    ,'Clear-CsOCEContext'
	,'Get-CsRegionContext'
	,'Set-CsRegionContext'
	,'Clear-CsRegionContext'
    ,'Get-CsMeetingMigrationTransactionHistory'
	,'Get-CsMasVersionedSchemaData'
	,'Get-CsBusinessVoiceDirectoryDiagnosticData'
	,'Get-CsCloudTenant'
	,'Get-CsCloudUser'
	,'Get-CsHostingProvider'
    ,'Set-CsTenantUserBackfill'
	,'Invoke-CsCustomHandlerNgtprov'
	,'New-CsSdgDeviceTaggingRequest'
    ,'Get-CsMoveTenantServiceInstanceTaskStatus'
	,'Move-CsTenantServiceInstance'
	,'Move-CsTenantCrossRegion'
	,'Invoke-CsDirectObjectSync'
#OCE exports end
)
# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
    'Add-TeamChannelUser'
    ,'Add-TeamUser'
    ,'Connect-MicrosoftTeams'
    ,'Disconnect-MicrosoftTeams'
    ,'Set-TeamsEnvironmentConfig'
    ,'Clear-TeamsEnvironmentConfig'
    ,'Get-AssociatedTeam'
    ,'Get-MultiGeoRegion'
    ,'Get-Operation'
    ,'Get-SharedWithTeam'
    ,'Get-SharedWithTeamUser'
    ,'Get-Team'
    ,'Get-TeamAllChannel'
    ,'Get-TeamChannel'
    ,'Get-TeamChannelUser'
    ,'Get-TeamIncomingChannel'
    ,'Get-TeamsApp'
    ,'Get-TeamUser'
    ,'Get-CsTeamsMessagingPolicy'
    ,'Get-CsTeamsMeetingPolicy'
    ,'Get-CsOnlineVoicemailPolicy'
    ,'Get-CsOnlineVoicemailValidationConfiguration'
    ,'Get-CsTeamsFeedbackPolicy'
    ,'Get-CsTeamsUpdateManagementPolicy'
    ,'Get-CsTeamsChannelsPolicy'
    ,'Get-CsTeamsMeetingBrandingPolicy'
    ,'Get-CsTeamsEmergencyCallingPolicy'
    ,'Get-CsTeamsCallHoldPolicy'
    ,'Get-CsTeamsMessagingConfiguration'
	,'Get-CsTeamsVoiceApplicationsPolicy'
    ,'Get-CsTeamsEventsPolicy'
    ,'Get-CsTeamsCallingPolicy'
    ,'Get-CsExternalAccessPolicy'
    ,'Get-CsTeamsAppPermissionPolicy'
    ,'Get-CsTeamsAppSetupPolicy'
    ,'Get-CsTeamsFirstPartyMeetingTemplateConfiguration'
    ,'Get-CsTeamsMeetingTemplatePermissionPolicy'
    ,'Get-CsLocationPolicy'
    ,'Get-CsTeamsCarrierEmergencyCallRoutingPolicy'
    ,'Grant-CsTeamsMeetingBrandingPolicy'
    ,'Grant-CsExternalAccessPolicy'
    ,'Grant-CsTeamsCallingPolicy'
	,'Grant-CsTeamsAppPermissionPolicy'
	,'Grant-CsTeamsAppSetupPolicy'
    ,'Grant-CsTeamsEventsPolicy',
    ,'Grant-CsTeamsMeetingTemplatePermissionPolicy'
    ,'Grant-CsTeamsCarrierEmergencyCallRoutingPolicy'
    ,'New-Team'
    ,'New-TeamChannel'
    ,'New-TeamsApp'
    ,'New-CsTeamsMessagingPolicy'
    ,'New-CsTeamsMeetingPolicy'
    ,'New-CsOnlineVoicemailPolicy'
    ,'New-CsTeamsFeedbackPolicy'
    ,'New-CsTeamsUpdateManagementPolicy'
    ,'New-CsTeamsChannelsPolicy'
    ,'New-CsTeamsMeetingBrandingTheme'
    ,'New-CsTeamsMeetingBackgroundImage'
    ,'New-CsTeamsNdiAssuranceSlate'
    ,'New-CsTeamsMeetingBrandingPolicy'
    ,'New-CsTeamsEmergencyCallingPolicy'
    ,'New-CsTeamsEmergencyCallingExtendedNotification'
    ,'New-CsTeamsCallHoldPolicy'
    ,'New-CsTeamsVoiceApplicationsPolicy'
    ,'New-CsTeamsEventsPolicy'
    ,'New-CsTeamsCallingPolicy'
    ,'New-CsExternalAccessPolicy'
    ,'New-CsTeamsAppPermissionPolicy'
    ,'New-CsTeamsAppSetupPolicy'
    ,'New-CsTeamsMeetingTemplatePermissionPolicy'
    ,'New-CsLocationPolicy'
    ,'New-CsTeamsCarrierEmergencyCallRoutingPolicy'
    ,'New-CsTeamsHiddenMeetingTemplate'
    ,'Remove-SharedWithTeam'
    ,'Remove-Team'
    ,'Remove-TeamChannel'
    ,'Remove-TeamChannelUser'
    ,'Remove-TeamsApp'
    ,'Remove-TeamUser'
    ,'Remove-CsTeamsMessagingPolicy'
    ,'Remove-CsTeamsMeetingPolicy'
    ,'Remove-CsOnlineVoicemailPolicy'
    ,'Remove-CsTeamsFeedbackPolicy'
    ,'Remove-CsTeamsUpdateManagementPolicy'
    ,'Remove-CsTeamsChannelsPolicy'
    ,'Remove-CsTeamsMeetingBrandingPolicy'
    ,'Remove-CsTeamsEmergencyCallingPolicy'
    ,'Remove-CsTeamsCallHoldPolicy'
    ,'Remove-CsTeamsVoiceApplicationsPolicy'
    ,'Remove-CsTeamsEventsPolicy'
    ,'Remove-CsTeamsCallingPolicy'
    ,'Remove-CsExternalAccessPolicy'
    ,'Remove-CsTeamsAppPermissionPolicy'
    ,'Remove-CsTeamsAppSetupPolicy'
    ,'Remove-CsTeamsMeetingTemplatePermissionPolicy'
    ,'Remove-CsLocationPolicy'
    ,'Remove-CsTeamsCarrierEmergencyCallRoutingPolicy'
    ,'Set-Team'
    ,'Set-TeamArchivedState'
    ,'Set-TeamChannel'
    ,'Set-TeamPicture'
    ,'Set-TeamsApp'
    ,'Set-CsTeamsMessagingPolicy'
    ,'Set-CsTeamsMeetingPolicy'
    ,'Set-CsOnlineVoicemailPolicy'
    ,'Set-CsOnlineVoicemailValidationConfiguration'
    ,'Set-CsTeamsFeedbackPolicy'
    ,'Set-CsTeamsUpdateManagementPolicy'
    ,'Set-CsTeamsChannelsPolicy'
    ,'Set-CsTeamsMeetingBrandingPolicy'
    ,'Set-CsTeamsEmergencyCallingPolicy'
    ,'Set-CsTeamsCallHoldPolicy'
    ,'Set-CsTeamsMessagingConfiguration'
	,'Set-CsTeamsVoiceApplicationsPolicy'
    ,'Set-CsTeamsEventsPolicy'
    ,'Set-CsTeamsCallingPolicy'
    ,'Set-CsExternalAccessPolicy'
    ,'Set-CsTeamsAppPermissionPolicy'
    ,'Set-CsTeamsAppSetupPolicy'
    ,'Set-CsTeamsFirstPartyMeetingTemplateConfiguration'
    ,'Set-CsTeamsMeetingTemplatePermissionPolicy'
    ,'Set-CsLocationPolicy'
    ,'Set-CsTeamsCarrierEmergencyCallRoutingPolicy'



#preview    ,'Add-TeamsAppInstallation'
#preview    ,'Get-TeamsAppInstallation'
    ,'Get-TeamTargetingHierarchyStatus'
#preview    ,'Remove-TeamsAppInstallation'
    ,'Remove-TeamTargetingHierarchy'
    ,'Set-TeamTargetingHierarchy'
#preview    ,'Update-TeamsAppInstallation'
#preview    ,'Get-LicenseReportForChangeNotificationSubscription'
 )

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Office365', 'MicrosoftTeams', 'Teams'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/MicrosoftDocs/office-docs-powershell/master/teams/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams'

        # A URL to an icon representing this module.
        IconUri = 'https://statics.teams.microsoft.com/evergreen-assets/apps/teamscmdlets_largeimage.png'

        # Appends prerelease string to version
        Prerelease = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
 **5.2.0-GA** (The project - MicrosoftTeams contains changes till this release)
- Contains a new implementation of [New|Get|Set|Remove|Grant]-CsTeamsAppPermissionPolicy, [New|Get|Set|Remove|Grant]-CsTeamsAppSetupPolicy, [New|Get|Set|Remove|Grant]-CsTeamsEventsPolicy, [New|Get|Set|Remove|Grant]-CsExternalAccessPolicy, [New|Get|Set|Remove|Grant]-CsTeamsCallingPolicy. Functionality remains the same as previous implementation.
- [BREAKING CHANGE] Updates Teams Shifts Connection cmdlets to separate connections and connection instances. The following changes apply as part of it:
  - Releases [New|Get|Set|Update]-CsTeamsShiftsConnection cmdlets.
  - Updates [New|Set|Update]-CsTeamsShiftsConnectionInstance cmdlets. Added ConnectionId & individual sync scenario parameters. Removed EnabledConnectorScenario, EnabledWfiScenario & ConnectorId parameters. Returns updated connection instance object.
  - Updates Get-CsTeamsShiftsConnectionInstance cmdlet. Returns updated connection instance object.
  - Updates Get-CsTeamsShiftsConnectionErrorReport. Added ConnectionId parameter.
  - Updates Get-CsTeamsShiftsConnectionWfmTeam. Added ConnectionId parameter.
  - Updates Get-CsTeamsShiftsConnectionConnector cmdlet. Returns updated supported connectors object.
  - Removed New-CsTeamsShiftsConnectionTeamMap cmdlet.
- Updates [New|Set]-CsAutoAttendant, [New|Set]-CsCallQueue cmdlets. Added HideAuthorizedUsers parameter.
- Releases [Set|Clear]-TeamsEnvironmentConfig cmdlets.
- Releases [Get|Set]-CsTeamsSettingsCustomApp cmdlets.
- Fixes ComplianceRecordingPolicy and ComplianceRecordingApplication cmdlets.

- The complete release notes can be found in the below link:
https://docs.microsoft.com/MicrosoftTeams/teams-powershell-release-notes
'@
    } # End of PSData hashtable
} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}

# SIG # Begin signature block
# MIInkwYJKoZIhvcNAQcCoIInhDCCJ4ACAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBFnt3/qdk/61es
# TE3nBGoHhqQJDTAs/Y+JLb3bt/FjzqCCDXYwggX0MIID3KADAgECAhMzAAADTrU8
# esGEb+srAAAAAANOMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMwMzE2MTg0MzI5WhcNMjQwMzE0MTg0MzI5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDdCKiNI6IBFWuvJUmf6WdOJqZmIwYs5G7AJD5UbcL6tsC+EBPDbr36pFGo1bsU
# p53nRyFYnncoMg8FK0d8jLlw0lgexDDr7gicf2zOBFWqfv/nSLwzJFNP5W03DF/1
# 1oZ12rSFqGlm+O46cRjTDFBpMRCZZGddZlRBjivby0eI1VgTD1TvAdfBYQe82fhm
# WQkYR/lWmAK+vW/1+bO7jHaxXTNCxLIBW07F8PBjUcwFxxyfbe2mHB4h1L4U0Ofa
# +HX/aREQ7SqYZz59sXM2ySOfvYyIjnqSO80NGBaz5DvzIG88J0+BNhOu2jl6Dfcq
# jYQs1H/PMSQIK6E7lXDXSpXzAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUnMc7Zn/ukKBsBiWkwdNfsN5pdwAw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMDUxNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAD21v9pHoLdBSNlFAjmk
# mx4XxOZAPsVxxXbDyQv1+kGDe9XpgBnT1lXnx7JDpFMKBwAyIwdInmvhK9pGBa31
# TyeL3p7R2s0L8SABPPRJHAEk4NHpBXxHjm4TKjezAbSqqbgsy10Y7KApy+9UrKa2
# kGmsuASsk95PVm5vem7OmTs42vm0BJUU+JPQLg8Y/sdj3TtSfLYYZAaJwTAIgi7d
# hzn5hatLo7Dhz+4T+MrFd+6LUa2U3zr97QwzDthx+RP9/RZnur4inzSQsG5DCVIM
# pA1l2NWEA3KAca0tI2l6hQNYsaKL1kefdfHCrPxEry8onJjyGGv9YKoLv6AOO7Oh
# JEmbQlz/xksYG2N/JSOJ+QqYpGTEuYFYVWain7He6jgb41JbpOGKDdE/b+V2q/gX
# UgFe2gdwTpCDsvh8SMRoq1/BNXcr7iTAU38Vgr83iVtPYmFhZOVM0ULp/kKTVoir
# IpP2KCxT4OekOctt8grYnhJ16QMjmMv5o53hjNFXOxigkQWYzUO+6w50g0FAeFa8
# 5ugCCB6lXEk21FFB1FdIHpjSQf+LP/W2OV/HfhC3uTPgKbRtXo83TZYEudooyZ/A
# Vu08sibZ3MkGOJORLERNwKm2G7oqdOv4Qj8Z0JrGgMzj46NFKAxkLSpE5oHQYP1H
# tPx1lPfD7iNSbJsP6LiUHXH1MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGXMwghlvAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAANOtTx6wYRv6ysAAAAAA04wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIFUqDTdvcXVrKrz82e6sKn4a
# SGdxzCoiE8sTVdIN04OLMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEA16GLOe5UFEHBJFXJUty2xNV1L7sD8y0U5Z0F+Puc4tgmPj+Ffqd9YhJN
# jG5pVfkvLXJNVwJbBD/YkEER100lKdmahkbd7gQUd4Wb+cFIwOEbwQtuLK5PkdwC
# /IlMRHdoVAjEGA+AAdi6Q9+N2VLcALATs1YjK13bIfn6rq+i8JEnEpWk4A4wNx6H
# 2EL9NVS4B4Bjmyd0E+0veRVsTo/yUWf4lO0DNiT5V9gN7avo+xTUxNT4+0qIJ2DK
# 9Pm+275DnXdHCwalsX+GzlB/4+644tDQ1uUs+NuRalkaBXdWIMpw0gcsP+9kek2N
# AiEylkqmH4VFiC4Bb+aiVX6e98jQQKGCFv0wghb5BgorBgEEAYI3AwMBMYIW6TCC
# FuUGCSqGSIb3DQEHAqCCFtYwghbSAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFRBgsq
# hkiG9w0BCRABBKCCAUAEggE8MIIBOAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCCsnu/3NMDiNn8SQAzXwklEsgqvAC4qq8Px5GyjY4k54wIGZF1eR5b4
# GBMyMDIzMDUxMjEzMTYwNi4wNDhaMASAAgH0oIHQpIHNMIHKMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjoyMjY0LUUz
# M0UtNzgwQzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCC
# EVQwggcMMIIE9KADAgECAhMzAAABwT6gg5zgCa/FAAEAAAHBMA0GCSqGSIb3DQEB
# CwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTIyMTEwNDE5MDEy
# N1oXDTI0MDIwMjE5MDEyN1owgcoxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMx
# JjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNOOjIyNjQtRTMzRS03ODBDMSUwIwYDVQQD
# ExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG9w0BAQEF
# AAOCAg8AMIICCgKCAgEA5LHXMydw2hUC4pJU0I5uPJnMeRm8LKC4xaIDu3Fxx3Ip
# Z/We2qXLj4NOmow/WPFeY4vaT4/S4T9xoDsFGg5wEJM6OLZVfa7BUNu0tDt4rkl7
# QBYNHzz6pcr9bwaq2qm7x6P9yi5W0Y8sjoj+QTgtmmXoxCoNXhJ1oG6GbqADQXDZ
# kTcDjIAiteE6TxrhBpIb7e6upifTGZNfcChPfuzHq61FSIwJ0XCxcaR1BwAlSKhb
# /NUOuQGPr9Zzd6OnIcA+RctxwKgfOKB9aWEEHlt0jhKKgpEBvcJnMMP+WaTwmMho
# b1e+hoCEFx/nI0YHupi6082kFdNFraE72msOYQrwrUyWCeSmN202LZDpTzxZVty6
# QrBOk+f+BErsR+M5evkKuUTWVJHI3vtNgb6K5+gk6EuQw0ocsDdspiPp+qlxBaW5
# 0yUbr6wnfzYjJh7QkPcfBIZbJAhWQHaV0uS3T7OkObdCssCRMWH7VWUAeSbemuUq
# OXCR7rdpFTfY/SXKO9lCIQBAQSh+wzwh5Zv1b+jT2zWwVl82By3YHmST8b8CKnRX
# SCjLtgoyy7ERLwkbzPIkCfBXcyVneC1w2/wUnqPiAjK0wQfztfXFfoMQr8YUcLHn
# Atek8OVNPuRIV6bcERbF6rtFXmnjjD4ZwVxIZ/HM4cjeVGsEwkFA9XTzqX9W1P8C
# AwEAAaOCATYwggEyMB0GA1UdDgQWBBRfr2MJ6x7yE+gP5uX9xWGTwpRC+jAfBgNV
# HSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQhk5o
# dHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
# aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
# CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRz
# L01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNV
# HRMBAf8EAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMIMA0GCSqGSIb3DQEBCwUAA4IC
# AQBfuiaBgsecHvM90RZiTDlfHblL09r9X+5q9ckuMR0Bs1Sr5B2MALhT5Y0R3ggL
# ufRX6RQQbSc7WxRXIMr5tFEgB5zy/7Yg81Cn2dhTf1GzjCb7/n3wtJSGtr2QwHsa
# 1ehYWdMfi+ETLoEX1G79VPFrs0t6Giwpr74tv+CLE3s6m10VOwe80wP4yuT3eiFf
# qRV8poUFSdL2wclgQKoSwbCpbJlNC/ESaDQbbQFli9uO5j2f/G7S4TMG/gyyxvMQ
# 5QJui9Fw2s7qklmozQoX2Ah4aKubKe9/VZveiETNYl1AZPj0kj1g51VNyWjvHw+H
# z1xZekWIpfMXQEi0wrGdWeiW4i8l92rY3ZbdHsErFYqzh6FRFOeXgazNsfkLmwy+
# TK17mA7CTEUzaAWMq5+f9K4Y/3mhB4r6UristkWpdkPWEo8b9tbkdKSY00E+FS5D
# UtjgAdCaRBNaBu8cFYCbErh9roWDxc+Isv8yMQAUDuEwXSy0ExnIAlcVIrhzL40O
# sG2ca5R5BgAevGP1Hj9ej4l/y+Sh0HVcN9N6LmPDmI/MaU2rEZ7Y+jRfCZ1d+l5D
# ESdLXIxDTysYXkT+3VM/1zh6y2s0Zsb/3vPaGnp2zejwf2YlGWl1XpChNZTelF5e
# OCCfSzUUn3qHe7IyyDKhahgbnKpmwcEkMVBs+RHbVkNWqDCCB3EwggVZoAMCAQIC
# EzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
# AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBS
# b290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoX
# DTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
# b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
# dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIi
# MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC
# 0/3unAcH0qlsTnXIyjVX9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VG
# Iwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP
# 2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/P
# XfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIckw+DJj361
# VI/c+gVVmG1oO5pGve2krnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwB
# Sru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F37ZyL9t9
# X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M269e
# wvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLXpyDw
# wvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr
# 9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+e
# FnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAj
# BgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+n
# FV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEw
# PwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9j
# cy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3
# FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAf
# BgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBH
# hkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNS
# b29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUF
# BzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0Nl
# ckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4Swf
# ZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTC
# j/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu
# 2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/
# GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3D
# YXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbO
# xnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqO
# Cb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakURR6nxt67I
# 6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0
# zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+ANuOaM
# mdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNT
# TY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggLLMIICNAIBATCB+KGB0KSBzTCByjEL
# MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
# bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWlj
# cm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEmMCQGA1UECxMdVGhhbGVzIFRTUyBF
# U046MjI2NC1FMzNFLTc4MEMxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVAESKOtSK7RVVK+Si+aqFd0YSY+VPoIGD
# MIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
# BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQG
# A1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwDQYJKoZIhvcNAQEF
# BQACBQDoCIV6MCIYDzIwMjMwNTEyMTcyOTMwWhgPMjAyMzA1MTMxNzI5MzBaMHQw
# OgYKKwYBBAGEWQoEATEsMCowCgIFAOgIhXoCAQAwBwIBAAICCGIwBwIBAAICEfIw
# CgIFAOgJ1voCAQAwNgYKKwYBBAGEWQoEAjEoMCYwDAYKKwYBBAGEWQoDAqAKMAgC
# AQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQUFAAOBgQBmhlqK/hE9erC+
# mCiSowStkOLvdQjbCCYBtJMLW8ESG1ULHP7n2tuhbjeEkGdgf1mdOlOLntSGexti
# 20tN64v25OOpQAMXTs6WoMznEyWALxD0GYWVRNj1J6GAm1UYjcbusGQpjSS5HziM
# dvGo1OtAHM2O40dDG3Fq1nJ4CwZOqjGCBA0wggQJAgEBMIGTMHwxCzAJBgNVBAYT
# AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBU
# aW1lLVN0YW1wIFBDQSAyMDEwAhMzAAABwT6gg5zgCa/FAAEAAAHBMA0GCWCGSAFl
# AwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwLwYJKoZIhvcN
# AQkEMSIEIK/Zp2bObX3zw3W2N07HLcnGcJDLZdnIIsXBJA9KiJlFMIH6BgsqhkiG
# 9w0BCRACLzGB6jCB5zCB5DCBvQQgCrkg6tgYHeSgIsN3opR2z7EExWA0YkirkvVY
# STBgdtQwgZgwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
# bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
# aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAA
# AcE+oIOc4AmvxQABAAABwTAiBCCgsGyh7aiscUb7fxsjbTyoSpK5vHqlcDeBKky8
# Uw1e9zANBgkqhkiG9w0BAQsFAASCAgDbfm+ZgQYb5q5ht9Cwokt8g9TaKWe60zlZ
# py4jwqgLj+qwx4w8uKeyNKq089X4ILpDcAu1634Fk6Agk6NhQq9eC9IF4hp1z4Jw
# jdYn75Vt40jeBfuv2PjCuEqTCVDgXLoox7RmQc4nql8U3U7N9uapCFy90bMq2qua
# JFKcAskIam60Km0SJSIS7r+h024s8TYvic6uUBSgZPukj6OvFLAI1zv/P4p9oLpq
# 2S1I7uSQXypx7UdV0lhCIfRANt4vzGa8DvqZ9T2xpwEcguT5tT20LTAIjFecDV60
# h7DHxKpyrtnlixygS7r63YAID0dHvOrVa43Adk0ayFyb1UDfghObA+nKFtLcdbj5
# kSjQHFFMYpnYq34oNaHjZn3HUFDoSB6HFm0erSnoKwPEh4SZq75CoZIMeByjBMYc
# 6fY73rN50FRzxb9zVrRngVTBLVAntbVBj1LQSlAvoiSniZDwcmCt0L7H8o4t1gET
# 6Q1/q1w8Hp2Wk/1m1m0dKtaEM+40p/vxeZcCQa/ZiJLoZ4HbsRPVnp0hKjwf4QHU
# EaGHAsbjosRAogtkdAwEppUP0Qn50AlCO8Pg/5ylh1cHC3so78jl1tBT/O5+Im3w
# GLvXiWxwWU9ERsh4jaXmwAUidpOmN4O2m8gPXCPCkAd7Iwrg714/MbDQ3hneACaG
# 2e23/OxK0Q==
# SIG # End signature block
